// # create-prs.js
import fs from 'node:fs';
import ora from 'ora';
import simpleGit from 'simple-git';
import { Octokit } from '@octokit/rest';

await fs.promises.mkdir('src/yaml', { recursive: true });
await fs.promises.writeFile('src/yaml/test.yaml', 'hello: world\n');

const results = [
	{
		files: ['src/yaml/test.yaml'],
		branch: 'package/smf-16/one',
		message: 'Add smf-16:one',
	},
];

const baseDir = process.cwd();
const git = simpleGit({ baseDir });

try {
	await git.deleteLocalBranch('package/smf-16/one');
} catch {}
await git.checkout('main');

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
for (let result of results) {
	let spinner = ora(`Creating new branch ${result.branch}`).start();
	await git.checkoutLocalBranch(result.branch);
	spinner.succeed();
	spinner = ora('Adding files...').start();
	for (let file of result.files) {
		await git.add(file);
		spinner.text = `${file} added`;
	}
	spinner.succeed(`Added ${result.files}`);
	spinner = ora(`Creating commit`).start();
	await git.commit(result.message);
	spinner.succeed();

	const { data: pr } = await octokit.pulls.create({
		owner: 'sebamarynissen',
		repo: 'actions-playground',
		base: 'main',
		title: result.message,
		head: result.branch,
		body: 'This PR is generated by Octokit',
	});
	console.log(pr);

}
