on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release.
        required: true
        default: patch

jobs:
  test:
    runs-on: windows-latest
    outputs:
      url: ${{ steps.read-version.outputs.version }}
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release'))
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install
        run: npm ci
      - id: get-tag
        uses: ./.github/actions/get-tag
        with:
          version: ${{ github.event.inputs.version }}
      - run: echo ${{ steps.get-tag.outputs.version }}
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - run: npm version ${{ steps.get-tag.outputs.version }}

      - name: Push version bump
        run: git push origin main

      - id: read-version
        name: Read version
        uses: ./.github/actions/get-version

      - run: echo ${{ steps.read-version.outputs.npm-tag }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.read-version.outputs.version }}
          generate_release_notes: true
          files: index.html

  linux:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Echo
        run: echo ${{ needs.test.outputs.url }}
