name: Configure user

on:
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if (typeof github !== 'undefined') console.log('github', github);
            if (typeof octokit !== 'undefined') console.log('octokit', octokit);
